{{- if .Values.server.enabled }}
{{- if .Values.server.ingress.enabled -}}
{{- $extraPaths := .Values.server.ingress.extraPaths -}}
{{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.Version -}}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "gocd.fullname" . }}-server
  labels:
    app: {{ template "gocd.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    component: server
  annotations:
    {{- range $key, $value := .Values.server.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.server.ingress.ingressClassName }}
  ingressClassName: {{ .Values.server.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.server.ingress.hosts }}
  {{ $dot := .}}
  rules:
    {{- range $host := .Values.server.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
        {{ if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
        {{- end }}
          - path: {{ $.Values.server.ingress.path }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.Version }}
            pathType: {{ default "ImplementationSpecific" $.Values.server.ingress.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare "<1.19-0" $.Capabilities.KubeVersion.Version }}
              serviceName: {{ template "gocd.fullname" $dot }}-server
              servicePort: {{ $dot.Values.server.service.httpPort }}
              {{- else }}
              service:
                name: {{ template "gocd.fullname" $dot }}-server
                port:
                  number: {{ $dot.Values.server.service.httpPort }}
              {{- end }}
    {{- end }}
  {{- else }}
  {{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.Version }}
  backend:
    serviceName: {{ template "gocd.fullname" . }}-server
    servicePort: {{ .Values.server.service.httpPort }}
  {{- else }}
  defaultBackend:
    service:
      name: {{ template "gocd.fullname" . }}-server
      port:
        number: {{ .Values.server.service.httpPort }}
  {{- end -}}
  {{- end -}}
  {{- if .Values.server.ingress.tls }}
  tls:
{{ toYaml .Values.server.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
